frontend:
  development_repo: /workspaces/frontend

panel_iframe:
  portainer:
    title: "Portainer"
    url: "http://192.168.178.109:9000/#/containers"
    icon: mdi:docker
    require_admin: true
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
