# docker-compose.yml 
version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "9000:9000/tcp"
    enviroment:
      - TZ=Europe/Berlin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
